// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odzeikhtfwxaeqooukha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kemVpa2h0Znd4YWVxb291a2hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MTYxNzgsImV4cCI6MjA1NzA5MjE3OH0.f5izQxy04DYAvYnVRQqu52reZmQA20xiW89SsL23I3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);