// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://napzgsglbiovapmpdhah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hcHpnc2dsYmlvdmFwbXBkaGFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NTAwOTgsImV4cCI6MjA1ODAyNjA5OH0.hyRI2GOpWfVgZEFNpMUlH92m-kAvTMZAJYyiaPUl8fU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);